version: "3"
services:
  redis-server:
    image: redis:7.0.8-alpine
  node-app:
    image: nodejs # not needed because we are using Dockerfile
    restart: on-failure # or always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:8081"
